name: GitHub Actions Build and Deploy
on:
  push:
    branches:
    - main    
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 1. git checkout...
      uses: actions/checkout@v1

    - name: 2. setup nodejs...
      uses: actions/setup-node@v1

    - name: 3. install hexo...
      run: |
        npm install hexo-cli -g  --registry https://registry.npm.taobao.org
        npm i --save hexo-wordcount -g  --registry https://registry.npm.taobao.org 
        npm install --save hexo-deployer-git  --registry https://registry.npm.taobao.org
        npm install  --registry https://registry.npm.taobao.org

    - name: 4. hexo generate public files...
      run: |
        hexo clean
        hexo g
    
    # 提交到我们的存放静态资源的仓库

    - name: Build and Deploy
      run: 
        hexo d
