name: GitHub Actions Build and Deploy
on:
  push:
    branches:
    - main    
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout...
      uses: actions/checkout@v1

    - name: setup nodejs...
      uses: actions/setup-node@v1

    - name: install hexo...
      run: |
        npm install hexo-cli -g  --registry https://registry.npm.taobao.org
        
    - name: install hexo-wordcount...
      run: | 
        npm i --save hexo-wordcount -g  --registry https://registry.npm.taobao.org 

    - name: install hexo-deployer-git...
      run: |
        npm install --save hexo-deployer-git  --registry https://registry.npm.taobao.org

    - name: install npm depandence...
      run: |
        npm install  --registry https://registry.npm.taobao.org

    - name: hexo generate public files...
      run: |
        hexo clean
        hexo g
    
    # 提交到我们的存放静态资源的仓库

    - name: Build and Deploy
      run: 
        hexo d
