name: GitHub Actions Build and Deploy
on:
  push:
    branches:
    - main    
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout...
      uses: actions/checkout@v1

    - name: git version...
      run: |
        git --version

    - name: setup nodejs...
      uses: actions/setup-node@v1

    - name: install hexo...
      run: |
        npm install hexo-cli -g  --registry https://registry.npm.taobao.org
        
    - name: install hexo-wordcount...
      run: | 
        npm i --save hexo-wordcount -g  --registry https://registry.npm.taobao.org 

    - name: install hexo-deployer-git...
      run: |
        npm install --save hexo-deployer-git  --registry https://registry.npm.taobao.org

    - name: install npm depandence...
      run: |
        npm install  --registry https://registry.npm.taobao.org

    - name: Git config user.name
      run: 
        git config --global user.name xhlu

    - name: Git config user.email
      run:         
        git config --global user.email 2846154596@qq.com

    - name: Git config store credential
      run:         
        git config --global credential.helper store ${{ secrets.HEXO_VERITY }} 

    - name: hexo clean
      run: 
        hexo clean &&
        rm -rf .deploy_git  &&
        hexo g && 
        hexo d
