name: GitHub Actions Build and Deploy
on:
  push:
    branches:
    - main    
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout...
      uses: actions/checkout@v1

    - name: setup nodejs...
      uses: actions/setup-node@v1

    - name: install hexo...
      run: |
        npm install hexo-cli -g  --registry https://registry.npm.taobao.org
        
    - name: install hexo-wordcount...
      run: | 
        npm i --save hexo-wordcount -g  --registry https://registry.npm.taobao.org 

    - name: install hexo-deployer-git...
      run: |
        npm install --save hexo-deployer-git  --registry https://registry.npm.taobao.org

    - name: install npm depandence...
      run: |
        npm install  --registry https://registry.npm.taobao.org

    - name: hexo clean and gen HTML...
      run: |
        hexo clean
        hexo g

    # - name:  git config --global credential.helper store
    #   run: | 
    #     git config --global credential.helper store

    - name: Push md file to Github resp_md_file branch...
      uses: x-actions/gh-pages@release/v2
      with:
        GITHUB_EMAIL: "2846154596@qq.com"
        GITHUB_USERNAME: "xhlu"
        PUBLISH_REPO: https://${{ secrets.HEXO_VERITY }}@github.com/luxinhua/luxinhua.github.io.git
        PUBLISH_BRANCH: resp_md_file
        PUBLISH_DIR: ./source/_posts
        DEPLOY_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v2
    #   with:
    #     github_token: ${{ secrets.HEXO_VERITY }}
    #     publish_dir: ./public

    # - name: Finished to deploy
    #   run: |
    #     echo "Finished to deploy !!!"